### ISSUE TITLE
Explaning the Configuration and insatlation of the socket io and node js form real time chat system

### ISSUE THREAD

**Issue by usamamashkoor** [moemoe89/Simple-realtime-message-SocketIO-NodeJS-Laravel#1]
Hi 
i am trying to built a real time chat system using Laravel 5.1 and socket.io.But i am having problem in configuring the socket io node.js dependencies like you have installed in your project can you please kindly tell me how can i do this.
It will be really appreciated.
Thanks in advance

**Comment by pedram31** [comment]
Cannot find module './public/node_modules/socket.io'
there is no node_modules folder??

**Comment by findelallc** [comment]
try this before **npm install --prefix ./public/**. It's already documented.
