### ISSUE TITLE
thanks for the upload very helpful 

### ISSUE THREAD

**Issue by pedram31** [moemoe89/Simple-realtime-message-SocketIO-NodeJS-Laravel#2]
Cannot find module './public/node_modules/socket.io'
there is no node_modules folder??

**Comment by pedram31** [comment]
Okay it was entirely my fault!!
i was using vagrant and my socket.io was located somewhere else.
fix--- just install socket as explained by author:
npm install --prefix ./public/

**Comment by pedram31** [comment]
While installing the socket if you get the error like this:
`npm ERR! Linux 3.19.0-25-generic

## npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--prefix" "./public/"`

Fix--- use "--no-bin-links" after you installation command like this:
npm install --prefix ./public/ --no-bin-links

**Comment by moemoe89** [comment]
@pedram31 cool !
