### ISSUE TITLE
composer install showing problem

### ISSUE THREAD

**Issue by MahbbRah** [moemoe89/Simple-realtime-message-SocketIO-NodeJS-Laravel#5]
Warning: require(C:\xampp\htdocs\nodeServer\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\nodeServer\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\nodeServer\bootstrap/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\nodeServer\bootstrap\autoload.php on line 17
PHP Warning:  require(C:\xampp\htdocs\nodeServer\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\nodeServer\bootstrap\autoload.php on line 17
PHP Fatal error:  require(): Failed opening required 'C:\xampp\htdocs\nodeServer\bootstrap/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\nodeServer\bootstrap\autoload.php on line 17
Script php artisan clear-compiled handling the pre-update-cmd event returned with an error

  [RuntimeException]
  Error Output: PHP Warning:  require(C:\xampp\htdocs\nodeServer\bootstrap/..
  /vendor/autoload.php): failed to open stream: No such file or directory in
  C:\xampp\htdocs\nodeServer\bootstrap\autoload.php on line 17
  PHP Fatal error:  require(): Failed opening required 'C:\xampp\htdocs\nodeS
  erver\bootstrap/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR')
  in C:\xampp\htdocs\nodeServer\bootstrap\autoload.php on line 17

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

**Comment by mohammed-elattar** [comment]
using this line

composer install --no-scripts 

worked fine with me
